### PR TITLE
Added CacheListStorage + Mockery + tests

### PR DESCRIPTION
**Pull request by assertchris**
Not sure if you're gonna like the composer update...

I've called the class `CacheListStorage` because it's possible to make a map implementation.

### CODE REVIEW

**Comment by assertchris** [comment]
Woah, what is that error about?

**Comment by assertchris** [comment]
When I update with `--prefer-lowest`, I got the following:
screen shot 2015-01-10 at 6 19 01 pm

**Comment by mnapoli** [comment]
I've fixed tests with `--prefer-lowest` on master, and I've added it to Travis so that's it's continuously tested.

Regarding the failing build, this is because PHPUnit needs a FQN in `@covers` annotations, so `@covers CacheListStorage` is an invalid one.

There's one thing in `CacheListStorage` that's bothering me: `$this->id` is kind of like an auto-increment ID, but it lives in the class instance. In the next request, those IDs are back to 0, so getting/setting in the cache will overwrite/conflicts existing entries.

In the end, it looks a lot like a MapStorage except IDs are autogenerated, but this auto-generation is problematic. I'm wondering if it could be made into a MapStorage, I'm wondering about the use cases of ListStorage at all (that can't be done with a Map). The only + side is the auto-generated ID, but maybe this concept can be brought back to MapStorage?

E.g. `MapStorage::set($key, $data)` could autogenerate a key and return it if `$key` is null? I've been thinking about this because it would make sense for storages like Database, MongoDB (TBI), … Using MySQL without being able to use autoincrement is almost a show-stopper, but at the same time using it as a List without the Map (i.e. `get($id)`) is also a show stopper… So maybe all this can be made into a single interface?

As for storages that don't support auto-increment or stuff like that, we could just do like MongoDB: return a generated unique ID (`uniqid()`, sha like git or whatever).

FYI I'm also thinking of removing the `Storage` interface, I don't see many use cases (https://twitter.com/matthieunapoli/status/553877859186376704).

**Comment by assertchris** [comment]
https://github.com/mnapoli/BlackBox/issues/10
https://github.com/mnapoli/BlackBox/issues/11
https://github.com/mnapoli/BlackBox/issues/12

**Pull request closed without merging**
